---
- hosts: all
  gather_facts: no
  vars_files:
    - wifi.yml
    - pi_user.yml
    - ssh_keys.yml
  tasks:

    - name: Generate wpa_supplicant network block for {{wifi.network}}
      command: 'wpa_passphrase ''{{wifi.network}}'' ''{{wifi.password}}'''
      register: wpa_supplicant_network_block
      changed_when: false

    - name: Render wpa_supplicant configuration file
      template:
        src: files/wpa_supplicant.conf.j2
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
      become: true

    - name: Set localhost refence to new hostname
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1	localhost {{ hostname }}'
      become: true

    - name: Set hostname to new hostname
      shell: 'echo ''{{ hostname }}'' > /etc/hostname'
      become: true

    - name: Update pi user password
      shell: 'echo ''pi:{{ pi_user.password }}'' | chpasswd'
      become: true

    - name: Remove packages
      apt:
        name: ['default-jre', 'default-jre-headless', 'openjdk-7-jre', 'openjdk-7-jre-headless']
        state: absent
      become: true

    - name: Add repositories
      apt_repository:
        repo: deb http://ftp.debian.org/debian buster-backports main
        state: absent
      become: true
    # - name: Get GPG keys for repositories
    #   shell: |
    #     gpg --keyserver pgp.mit.edu --recv-keys 7638D0442B90D010 8B48AD6246925553
    #     gpg --armor --export 7638D0442B90D010 | apt-key add -
    #     gpg --armor --export 8B48AD6246925553 | apt-key add -
    #   become: true
    - name: Install packages
      apt:
        name: ['software-properties-common', 'git', 'avahi-daemon', 'nginx', 'toilet', 'python3', 'python3-venv', 'python3-pip', 'python-certbot-nginx']
        state: present
        update_cache: yes
      become: true
      # Needed an override to remove the ipv6 listener in /etc/nginx/sites-enabled/default
    - name: Copy font for MOTD
      copy:
        src: files/doom.flf
        dest: /usr/share/figlet/
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Set MOTD to ASCII art of hostname
      shell: 'echo ''{{ hostname }}'' | tr a-z A-Z | toilet --font doom > /etc/motd'
      become: true

    - name: Add SSH keys
      authorized_key:
        user: pi
        key: '{{ item }}'
        state: present
      with_items: '{{ ssh_keys }}'
      become: true

    - name: Resize file system to fit SD card (deployed pi only)
      command: 'resize2fs /dev/mmcblk0p2'
      when: deployed_pi
      become: true
# Home Assistant
# NGINX configuration
# Afraid.org DNS config
# LetsEncrypt daemon
# Sinclairstudios.net website?