---
- hosts: all
  gather_facts: no
  vars_files:
    - wifi.yml
    - pi_user.yml
    - ssh_keys.yml
  tasks:

    - name: Generate wpa_supplicant network block for {{wifi.network}}
      command: 'wpa_passphrase ''{{wifi.network}}'' ''{{wifi.password}}'''
      register: wpa_supplicant_network_block
      changed_when: false

    - name: Render wpa_supplicant configuration file
      template:
        src: files/wpa_supplicant.conf.j2
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
      become: true

    - name: Set localhost refence to {{ hostname }}
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1' 
        line: '127.0.0.1	localhost {{ hostname }}'
      become: true

    - name: Set hostname to {{ hostname }}
      shell: 'echo ''{{ hostname }}'' > /etc/hostname'
      become: true

    - name: Update pi user password
      shell: 'echo ''pi:{{ pi_user.password }}'' | chpasswd'
      become: true

    - name: Install the package "avahi-daemon"
      apt:
        name: avahi-daemon
        state: present

    - name: Add SSH keys
      authorized_key:
        user: pi
        key: '{{ item }}'
        state: present
      with_items: '{{ ssh_keys }}'
      become: true
