---
- hosts: all
  gather_facts: no
  vars_files:
    - wifi.yml
    - pi_user.yml
    - ssh_keys.yml
  tasks:

    - name: Generate wpa_supplicant network block for {{wifi.network}}
      command: 'wpa_passphrase ''{{wifi.network}}'' ''{{wifi.password}}'''
      register: wpa_supplicant_network_block
      changed_when: false

    - name: Render wpa_supplicant configuration file
      template:
        src: files/wpa_supplicant.conf.j2
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
      become: true

    - name: Set localhost refence to new hostname
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1	localhost {{ hostname }}'
      become: true

    - name: Set hostname to new hostname
      shell: 'echo ''{{ hostname }}'' > /etc/hostname'
      become: true

    - name: Update pi user password
      shell: 'echo ''pi:{{ pi_user.password }}'' | chpasswd'
      become: true

    - name: Remove packages
      apt:
        name: "{{item}}"
        state: absent
      become: true
      with_items:
        - default-jre
        - default-jre-headless
        - openjdk-7-jre
        - openjdk-7-jre-headless

    - name: Install packages
      apt:
        name: "{{item}}"
        state: present
      become: true
      with_items:
        - oracle-java8-jdk
        - avahi-daemon
        - toilet

    - name: Copy font for MOTD
      copy:
        src: files/doom.flf
        dest: /usr/share/figlet/
        owner: root
        group: root
        mode: 0644
      become: true

    - name: Set MOTD to ASCII art of hostname
      shell: 'echo ''{{ hostname }}'' | tr a-z A-Z | toilet --font doom > /etc/motd'
      become: true

    - name: Enable MOTD on SSH login
      shell: sed -i '/PrintMotd/ c\PrintMotd yes ' /etc/ssh/sshd_config
      become: true

    - name: Add SSH keys
      authorized_key:
        user: pi
        key: '{{ item }}'
        state: present
      with_items: '{{ ssh_keys }}'
      become: true

    - name: Resize file system to fit SD card (deployed pi only)
      command: 'resize2fs /dev/mmcblk0p2'
      when: deployed_pi
      become: true
